### ISSUE TITLE
插件消失 Plugins disappear

### ISSUE THREAD

**Issue by JieCrom** [4679/DalamudPlugins#1]
在作者提交API8更新和移除resizer后所有之前能找到该链接提供的CN插件都在dalamud里消失了，作者能解决下这个问题吗？非常感谢。
After submitting the API8 update and removed the resizer plugin, all the CN plugins provided by this link disappeared in dalamud. Can the author solve this problem? Thank you so much.

**Comment by 4679** [comment]
因为都已经有能用的了，glamourer现在獭爹自己维护了，haseltweaks直接用官方源，xivwindowresize进了官方库，lootmaster用lazyloot替代，等等
